#ifndef _webm_format_h_
#define _webm_format_h_

#ifdef __cplusplus
extern "C" {
#endif

enum ebml_video_interlaced_e
{
	EBML_VIDEO_FLAG_UNDETERMINED = 0,
	EBML_VIDEO_FLAG_INTERLACED = 1,
	EBML_VIDEO_FLAG_PROGRESSIVE = 2,
};

enum ebml_video_field_order_e
{
	EBML_VIDEO_FIELD_ORDER_PROGRESSIVE = 0,
	EBML_VIDEO_FIELD_ORDER_TTF = 1,
	EBML_VIDEO_FIELD_ORDER_UNDETERMINED = 2,
	EBML_VIDEO_FIELD_ORDER_BFF = 6,
	EBML_VIDEO_FIELD_ORDER_BFF_SWAPPED = 9,
	EBML_VIDEO_FIELD_ORDER_TTF_SWAPPED = 14,
};

enum ebml_video_stereo_mode_e
{
	EBML_VIDEO_STEREO_MODE_MONO = 0,
	EBML_VIDEO_STEREO_MODE_SIDE_BY_SIDE_LEFT = 1, // left eye first
	EBML_VIDEO_STEREO_MODE_TOP_BOTTOM_RIGHT = 2, // right eye first
	EBML_VIDEO_STEREO_MODE_TOP_BOTTOM_LEFT = 3, // left eye first
	EBML_VIDEO_STEREO_MODE_CHECKBOARD_RIGHT = 4, // right eye first
	EBML_VIDEO_STEREO_MODE_CHECKBOARD_LEFT = 5, // left eye first
	EBML_VIDEO_STEREO_MODE_ROW_INTERLEAVED_RIGHT = 6, // right eye first
	EBML_VIDEO_STEREO_MODE_ROW_INTERLEAVED_LEFT = 7, // left eye first
	EBML_VIDEO_STEREO_MODE_COLUMN_INTERLEAVED_RIGHT = 8, // right eye first
	EBML_VIDEO_STEREO_MODE_COLUMN_INTERLEAVED_LEFT = 9, // left eye first
	EBML_VIDEO_STEREO_MODE_ANAGLYPH_CYAN_RED = 10, // cyan/red
	EBML_VIDEO_STEREO_MODE_SIDE_BY_SIDE_RIGHT = 11, // right eye first
	EBML_VIDEO_STEREO_MODE_ANAGLYPH_GREEN_MAGENTA = 12, // green/megenta
	EBML_VIDEO_STEREO_MODE_BOTH_EYES_LACED_IN_ONE_BLOCK_LEFT = 13, // left eye first
	EBML_VIDEO_STEREO_MODE_BOTH_EYES_LACED_IN_ONE_BLOCK_RIGHT = 14, // right eye first
};

enum ebml_video_display_unit_e
{
	EBML_VIDEO_DISPLAY_UNIT_PIXELS = 0,
	EBML_VIDEO_DISPLAY_UNIT_CETIMETERS = 1,
	EBML_VIDEO_DISPLAY_UNIT_INCHES = 2,
	EBML_VIDEO_DISPLAY_UNIT_ASPECT_RATION = 3,
	EBML_VIDEO_DISPLAY_UNIT_UNKNOWN = 4,
};

enum ebml_video_aspect_ratio_type_e
{
	EBML_VIDEO_ASPECT_RATIO_TYPE_FREE_RESIZING = 0,
	EBML_VIDEO_ASPECT_RATIO_TYPE_KEEP_ASPECT_RATIOn = 1,
	EBML_VIDEO_ASPECT_RATIO_TYPE_FIXED = 2,
};

enum ebml_video_color_matrix_coefficients_t
{
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_IDENTIY = 0,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_ITU_R_BT709 = 1,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_UNSPECIFIED = 2,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_RESERVED = 3,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_US_FCC_73_682 = 4,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_ITU_R_BT_470BG = 5,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_SMPTE_170M = 6,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_SMPTE_240M = 7,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_YCOCG = 8,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_BT2020_NON_CONSTANT_LUMINANCE = 9,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_BT2020_CONSTANT_LUMINANCE = 10,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_SMPTE_ST_2085 = 11,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_CHROMA_DERIVED_NON_CONSTANT_LUMINANCE = 12,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_CHROMA_DERIVED_CONSTANT_LUMINANCE = 13,
	EBML_VIDEO_COLOR_MATRIX_COEFFICIENTS_ITU_R_BT_2100_0 = 14,
};

enum ebml_video_color_range_e
{
	EBML_VIDEO_COLOR_RANGE_UNSPECIFIED = 0,
	EBML_VIDEO_COLOR_RNAGE_BROADCAST_RANGE,
	EBML_VIDEO_COLOR_RNAGE_FULL_RANGE,
	EBML_VIDEO_COLOR_RNAGE_MATRIX_COEFFICIENTS,
};

enum ebml_video_color_transfer_characteristics_e
{
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_RESERVED = 0,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_ITU_R_BT_709 = 1,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_UNSPECIFIED = 2,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_GAMMA_2_2_CURVE_BT_470M = 4,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_GAMMA_2_8_CURVE_BT_470BG = 5,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_SMPTE_170M = 6,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_SMPTE_240M = 7,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_LINEAR = 8,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_LOG = 9,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_LOG_SQRT = 10,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_IEC_61966_2_4 = 11,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_ITU_R_BT_1361_EXTENDED_COLOUR_GAMUT = 12,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_IEC_61966_2_1 = 13,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_ITU_R_BT_2020_10BIT = 14,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_ITU_R_BT_2020_12BIT = 15,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_ITU_R_BT_2100_PERCEPTUAL_QUANTIZATION = 16,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_SMPTE_ST_428_1 = 17,
	EBML_VIDEO_COLOR_TRANSFER_CHARACTERISTICS_ARIB_STD_B67_HLG = 18,
};

enum ebml_video_color_primaries_e
{
	EBML_VIDEO_COLOR_PRIMARIES_RESERVED = 0,
	EBML_VIDEO_COLOR_PRIMARIES_ITU_R_BT_709 = 1,
	EBML_VIDEO_COLOR_PRIMARIES_UNSPECIFIED = 2,
	EBML_VIDEO_COLOR_PRIMARIES_ITU_R_BT_470M = 4,
	EBML_VIDEO_COLOR_PRIMARIES_ITU_R_BT_470BG_BT_601_625 = 5,
	EBML_VIDEO_COLOR_PRIMARIES_ITU_R_BT_601_525_TMPTE_170M = 6,
	EBML_VIDEO_COLOR_PRIMARIES_SMPTE_240M = 7,
	EBML_VIDEO_COLOR_PRIMARIES_FILM = 8,
	EBML_VIDEO_COLOR_PRIMARIES_ITU_R_BT_2020 = 9,
	EBML_VIDEO_COLOR_PRIMARIES_SMPTE_ST_428_1 = 10,
	EBML_VIDEO_COLOR_PRIMARIES_SMPTE_RP_432_2 = 11,
	EBML_VIDEO_COLOR_PRIMARIES_SMPTE_EG_432_2 = 12,
	EBML_VIDEO_COLOR_PRIMARIES_EBU_TECH_3212E_JEDEC_P22_PHOSPHORS = 22,
};

enum ebml_video_projection_type_e
{
	EBML_VIDEO_PROJECTION_RECTANGULAR = 0,
	EBML_VIDEO_PROJECTION_EQUIRECTANGULAR = 1,
	EBML_VIDEO_PROJECTION_CUBEMAP = 2,
	EBML_VIDEO_PROJECTION_MESH = 3,
};

#ifdef __cplusplus
}
#endif
#endif /* !_webm_format_h_ */
