#ifndef _rtmp_event_h_
#define _rtmp_event_h_

// 7.1.3. Shared Object Message (19, 16) (p24)
// AMF Shared Object Message Event
enum
{
	RTMP_AMF_EVENT_USE				= 1,
	RTMP_AMF_EVENT_RELEASE			= 2,
	RTMP_AMF_EVENT_REQUEST_CHANGE	= 3,
	RTMP_AMF_EVENT_CHANGE			= 4,
	RTMP_AMF_EVENT_SUCCESS			= 5,
	RTMP_AMF_EVENT_SEND_MESSAGE		= 6,
	RTMP_AMF_EVENT_STATUS			= 7,
	RTMP_AMF_EVENT_CLEAR			= 8,
	RTMP_AMF_EVENT_REMOVE			= 9,
	RTMP_AMF_EVENT_REQUEST_REMOVE	= 10,
	RTMP_AMF_EVENT_USE_SUCCESS		= 11,
};

// 7.1.7. User Control Message Events (p27)
enum
{
	RTMP_USER_EVENT_STREAM_BEGIN		= 0,
	RTMP_USER_EVENT_STREAM_EOF			= 1,
	RTMP_USER_EVENT_STREAM_DRY			= 2,
	RTMP_USER_EVENT_SET_BUFFER_LENGTH	= 3,
	RTMP_USER_EVENT_STREAM_IS_RECORD	= 4,

	RTMP_USER_EVENT_PING_REQUEST		= 6,
	RTMP_USER_EVENT_PING_RESPONSE		= 7,
};

#endif /* !_rtmp_event_h_ */
